### ISSUE TITLE
About sdk2.0.15

### ISSUE THREAD

**Issue by AutumnLeavesss** [Michael-List/Orbbec_Astra_Example_Android#1]
do you have example for the android  sdk 2.0.15?
update the sdk 2.0.15 already changed inner method,can you give me a demo?

**Comment by Michael-List** [comment]
I'm sorry but I don't have the hardware (camera + android dev board) anymore. But if you make a new version feel free to make a pull request.

**Comment by Michael-List** [comment]
Closed due to inactivity
