### ISSUE TITLE
how to get DepthStream and ColorStream?

### ISSUE THREAD

**Issue by sweetValley** [Michael-List/Orbbec_Astra_Example_Android#2]
Can you get the DepthStream and ColorStream?
I have tried that replacing PointStream to DepthStream or ColorStream in code,but it throw exception while executing "DepthStream depthStream = DepthStream.get(reader);",the exception is "java.lang.UnsupportedOperationException: Invalid operation"

Help me please,thank you very much!

**Comment by Michael-List** [comment]
I updated the repo (Commit: 264dc73fd3100f4f6b09665815d0e15fb3de9edb) and now there is an example for DepthStream which i used in my project.

Unfortunately I cannot test the code because i don't have the hardware. But you are welcome to send a pull request for improvements

**Comment by Michael-List** [comment]
Closed due to inactivity
