### ISSUE TITLE
About astra SDK for android

### ISSUE THREAD

**Issue by 1010chenhao** [Michael-List/Orbbec_Astra_Example_Android#4]
Hi,thanks for the code you shared~
I am new about this field,I just download the latest SDK for android from astra's website,however,it does not suit with my camera(or os) very well.So I wonder  if you have the old version SDK for android and then I could have a try on it.Thanks!

**Comment by Michael-List** [comment]
I only have this file in my repo: https://github.com/Michael-List/Orbbec_Astra_Example_Android/blob/master/app/libs/astra-android-release-v2.0.12-b48cd2945b.aar
I don't know if this is everything you need.

(Sorry for the late reply, but I missed the notification for this issue)
